version: '3'

services:
  mysql_db:
    container_name: trace_mysql
    image: "mysql:latest"
    restart: always
    ports:
         - "3306:3306"
    environment:
         - "MYSQL_ROOT_PASSWORD=password"
    volumes:
         - "/home/data/mysql:/var/lib/mysql"
  myadmin:
    container_name: trace_myadmin
    image: "phpmyadmin/phpmyadmin:latest"
    environment:
        PMA_HOST: mysql_db
        PMA_PORT: 3306
    links:
          - mysql_db
    depends_on:
          - mysql_db
    ports:
         - "8080:80"
  mongodb:
    container_name: trace_mongo
    image: "mongo:latest"
    ports:
         - "27017:27017"
    volumes:
         - "/home/data/mongo:/data/db"
    command: >
         mongod --auth mongo --eval db.createUser({ user: 'hasher', pwd: 'password', roles: [ { role: "readWrite", db: "hashes" } ] });
  elastic:
    container_name: trace_elastic
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.3.0"
    ports:
         - "9200:9200"
    environment:
         - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
         - xpack.security.enabled=false
         - http.cors.enabled=true
         - http.cors.allow-origin="*"
         - transport.host=127.0.0.1
         - http.host=0.0.0.0
    volumes:
         - "/home/data/elastic:/usr/share/elasticsearch/data"
  nats_server:
    container_name: trace_nats
    image: "nats"
    ports:
        - "4222:4222"
        - "6222:6222"
        - "8222:8222"
  minio_server:
    container_name: trace_minio
    image: "minio/minio"
    env_file: variables1.env
    volumes:
         - "/home/data/minio/data:/data"
         - "/home/data/minio/config:/root/.minio"
    command: server /data